# openapi.yaml
openapi: 3.0.0
info:
  title: Modular API Example
  version: 1.0.0
  description: API modularizada con Swagger YAML y $ref

servers:
  - url: http://localhost:3000/api

tags:
  - name: auth
    description: Operaciones relacionada con la autentificación de usuarios

paths:
  /auth/register:
    $ref: "./paths/auth/auth.register.yaml"
  /auth/login:
    $ref: "./paths/auth/auth.login.yaml"
